.Dd April 10, 2015
.Dt ELIXIRC 1
.Os
.Sh NAME
.Nm elixirc
.Nd The Elixir compiler
.Sh SYNOPSIS
.Nm
.Op Ar OPTIONS
.Ar
.Sh DESCRIPTION
The compiler is intended for compilation one or more files containing the Elixir source code. The files should have the extension
.Em .ex .
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl o Ar directory
Places the output file in the specified directory. If the directory is not specified via the option, the current working directory will be used for the purpose.
.It Fl -erl Ar parameters
Serves the same purpose as ELIXIR_ERL_OPTIONS
.Pq see the Sy ENVIRONMENT No section .
.It Fl -ignore-module-conflict
Disables warnings when a module was previously defined.
.It Fl -no-debug-info
Disables producing debugging information.
.It Fl -no-docs
Disables generating documentation.
.It Fl -warnings-as-errors
Makes all warnings into errors.
.It Fl -verbose
Activates verbose mode.
.It Fl -
Separates the options passed to the compiler from the options passed to the executed code.
.El
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev ELIXIR_ERL_OPTIONS
Allows passing parameters to the Erlang runtime.
.It Ev ERL_COMPILER_OPTIONS
Allows passing parameters to the Erlang compiler
.Pq see Xr erlc 1 .
.El
.Sh SEE ALSO
.Xr elixir 1 ,
.Xr iex 1 ,
.Xr mix 1
.Sh AUTHOR
This manual page contributed by Evgeny Golyshev.
.Sh INTERNET RESOURCES
.Bl -tag -width Ds
.It Main website: https://elixir-lang.org
.It Documentation: https://elixir-lang.org/docs.html
.El
