# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2021 The Elixir Team

excludes:
  paths:
    - pattern: "lib/elixir/pages/**/*"
      reason: "DOCUMENTATION_OF"
      comment: "Documentation"
    - pattern: "lib/elixir/scripts/**/*"
      reason: "BUILD_TOOL_OF"
      comment: "Build Tool"
    - pattern: "lib/ex_unit/examples/**/*"
      reason: "EXAMPLE_OF"
      comment: "Example"
    - pattern: "lib/*/test/**/*"
      reason: "TEST_OF"
      comment: "Tests"
    - pattern: "man/*"
      reason: "DOCUMENTATION_OF"
      comment: "Documentation"
    - pattern: ".github/**/*"
      reason: "BUILD_TOOL_OF"
      comment: "Documentation"
    - pattern: ".ort/**/*"
      reason: "BUILD_TOOL_OF"
      comment: "Documentation"

curations:
  license_findings:
    # Logos
    - path: "lib/elixir/pages/images/logo.png"
      reason: "NOT_DETECTED"
      comment: "Apply Trademark Policy to Elixir Logo"
      detected_license: "NONE"
      concluded_license: "LicenseRef-elixir-trademark-policy"
    - path: "lib/elixir/scripts/windows_installer/assets/Elixir.ico"
      reason: "NOT_DETECTED"
      comment: "Apply Trademark Policy to Elixir Logo"
      detected_license: "NONE"
      concluded_license: "LicenseRef-elixir-trademark-policy"

    # Version File
    - path: "VERSION"
      reason: "NOT_DETECTED"
      comment: "Apply Trademark Policy to VERSION file"
      detected_license: "NONE"
      concluded_license: "Apache-2.0"

    # Documentation Images
    - path: "lib/elixir/pages/images/**/*.png"
      reason: "NOT_DETECTED"
      comment: "Apply default license to all images"
      detected_license: "NONE"
      concluded_license: "Apache-2.0"

    # Test Fixtures
    - path: "lib/eex/test/fixtures/**/*"
      reason: "NOT_DETECTED"
      comment: "Apply default license to test fixtures"
      detected_license: "NONE"
      concluded_license: "Apache-2.0"
    - path: "lib/elixir/test/elixir/fixtures/**/*"
      reason: "NOT_DETECTED"
      comment: "Apply default license to test fixtures"
      detected_license: "NONE"
      concluded_license: "Apache-2.0"
    - path: "lib/ex_unit/test/fixtures/**/*"
      reason: "NOT_DETECTED"
      comment: "Apply default license to test fixtures"
      detected_license: "NONE"
      concluded_license: "Apache-2.0"
    - path: "lib/mix/test/fixtures/**/*"
      reason: "NOT_DETECTED"
      comment: "Apply default license to test fixtures"
      detected_license: "NONE"
      concluded_license: "Apache-2.0"

    # Unicode
    - path: "lib/elixir/unicode/*.txt"
      reason: "NOT_DETECTED"
      comment: "Apply default license to unicode files"
      detected_license: "NONE"
      concluded_license: "LicenseRef-scancode-unicode"

    # Wrongly Identified
    - path: "lib/elixir/pages/references/library-guidelines.md"
      reason: "INCORRECT"
      comment: |
        The guide mentions multiple licenses for users to choose from.
        It however is not licensed itself by the mentioned licenses.
      concluded_license: "Apache-2.0"
    - path: ".gitignore"
      reason: "INCORRECT"
      comment: "Ignored by ScanCode"
      detected_license: "NONE"
      concluded_license: "Apache-2.0"
    - path: ".gitattributes"
      reason: "INCORRECT"
      comment: "Ignored by ScanCode"
      detected_license: "NONE"
      concluded_license: "Apache-2.0"
    - path: "lib/elixir/scripts/windows_installer/.gitignore"
      reason: "INCORRECT"
      comment: "Ignored by ScanCode"
      detected_license: "NONE"
      concluded_license: "Apache-2.0"
    - path: "CONTRIBUTING.md"
      reason: "INCORRECT"
      comment: "Wrongly identified TSL license"
      detected_license: "Apache-2.0 OR NOASSERTION OR LicenseRef-scancode-tsl-2020"
      concluded_license: "Apache-2.0"
    - path: "OPEN_SOURCE_POLICY.md"
      reason: "INCORRECT"
      comment: "Wrongly identified NOASSERTION"
      detected_license: "NOASSERTION"
      concluded_license: "Apache-2.0"
  
  packages:
    - id: "SpdxDocumentFile:The Elixir Team:elixir-lang:"
      curations:
        concluded_license: "Apache-2.0 AND LicenseRef-scancode-unicode"
    - id: "SpdxDocumentFile:The Elixir Team:eex:"
      curations:
        concluded_license: "Apache-2.0"
        is_metadata_only: true
    - id: "SpdxDocumentFile:The Elixir Team:elixir:"
      curations:
        concluded_license: "Apache-2.0 AND LicenseRef-scancode-unicode"
        is_metadata_only: true
    - id: "SpdxDocumentFile:The Elixir Team:exunit:"
      curations:
        concluded_license: "Apache-2.0"
        is_metadata_only: true
    - id: "SpdxDocumentFile:The Elixir Team:iex:"
      curations:
        concluded_license: "Apache-2.0"
        is_metadata_only: true
    - id: "SpdxDocumentFile:The Elixir Team:logger:"
      curations:
        concluded_license: "Apache-2.0"
        is_metadata_only: true
    - id: "SpdxDocumentFile:The Elixir Team:mix:"
      curations:
        concluded_license: "Apache-2.0"
        is_metadata_only: true
