blank_issues_enabled: true

contact_links:
  - name: Discuss proposals
    url: https://groups.google.com/g/elixir-lang-core
    about: Send proposals for new ideas in the mailing list.
  - name: Ask questions
    url: https://elixirforum.com/
    about: Ask and answer questions on ElixirForum.

