# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2021 The Elixir Team

ort:
  enableRepositoryPackageCurations: true
  enableRepositoryPackageConfigurations: true

  scanner:
    skipConcluded: false
    includeFilesWithoutFindings: true

  analyzer:
    allowDynamicVersions: true
    enabledPackageManagers: [SpdxDocumentFile]

  reporter:
    reporters:
      SpdxDocument:
        options:
          creationInfoOrganization: The Elixir Team
          documentName: "Elixir Source SPDX Document"
