{'src/*', [
  warn_unused_vars,
  warn_export_all,
  warn_shadow_vars,
  warn_unused_import,
  warn_unused_function,
  warn_bif_clash,
  warn_unused_record,
  warn_deprecated_function,
  warn_obsolete_guard,
  strict_validation,
  warn_exported_vars,
  %% warn_missing_spec,
  %% warn_untyped_record,
  warnings_as_errors,
  debug_info,
  {outdir, "ebin/"}
]}.
