name: Nightly Release

on: 
  schedule:
    - cron: "*/10 * * * *"

jobs:
  delete_previous_nightly_and_tag: 
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
          ref: main
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true 
          tag_name: main-nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prepare_release:
    uses: ./.github/workflows/prepare-release.yml
    with:
      version: main-nightly

  publish_pre_release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
          ref: main
      # NOTE: The `gh` command doesn't support edit release. It's needs to wait until they 
      # implement https://github.com/cli/cli/issues/1997. Temporary fixed by using `hub` instead.
      - uses: geertvdc/setup-hub@master
      - run: |
          hub release edit main-nightly --draft=false --prerelease
