name: Prepare Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  release_pre_built:
    strategy:
      fail-fast: true
      matrix:
        include:
          - otp: 23
            otp_version: 23.3
          - otp: 24
            otp_version: 24.1
            build_docs: build_docs
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
          ref: ${{ inputs.version }}
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          version-type: strict
      - name: Build Elixir Release
        run: |
          make Precompiled.zip
          mv Precompiled.zip elixir-otp-${{ matrix.otp }}.zip
          shasum -a 1 elixir-otp-${{ matrix.otp }}.zip > elixir-otp-${{ matrix.otp }}.zip.sha1sum
          shasum -a 256 elixir-otp-${{ matrix.otp }}.zip > elixir-otp-${{ matrix.otp }}.zip.sha256sum
          echo "$PWD/bin" >> $GITHUB_PATH
      - name: Upload Pre-built
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          vsn=$(cat VERSION)
          gh release upload --clobber "v${vsn}" \
            elixir-otp-${{ matrix.otp }}.zip \
            elixir-otp-${{ matrix.otp }}.zip.sha{1,256}sum
      - uses: actions/checkout@v2
        with:
          repository: elixir-lang/ex_doc
          ref: v0.26.0
          path: ex_doc
        if: ${{ matrix.build_docs }}
      - name: Build ex_doc
        if: ${{ matrix.build_docs }}
        run: |
          mv ex_doc ../ex_doc
          cd ../ex_doc
          ../elixir/bin/mix do local.rebar --force, local.hex --force, deps.get, compile
          cd ../elixir
      - name: Build Docs
        if: ${{ matrix.build_docs }}
        run: |
          make Docs.zip
          shasum -a 1 Docs.zip > Docs.zip.sha1sum
          shasum -a 256 Docs.zip > Docs.zip.sha256sum
      - name: Upload Docs
        if: ${{ matrix.build_docs }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          vsn=$(cat VERSION)
          gh release upload --clobber "v${vsn}" \
            Docs.zip \
            Docs.zip.sha{1,256}sum
