name: Publish docs

on:
  push:
    branches:
      - main
      - v*.*

env:
  ELIXIR_OPTS: "--warnings-as-errors"
  ERLC_OPTS: "warnings_as_errors"
  LANG: C.UTF-8
  AWS_S3_BUCKET: "s3.hex.pm"

jobs:
  release_pre_built:
    strategy:
      fail-fast: true
      matrix:
        include:
          - otp: 24
            otp_version: 24.3
          - otp: 25
            otp_version: 25.0
            build_docs: build_docs
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - uses: ./.github/workflows/release_pre_built
        with:
          otp_version: ${{ matrix.otp_version }}
          otp: ${{ matrix.otp }}
          build_docs: ${{ matrix.build_docs }}
      - name: Upload Docs to S3
        if: ${{ matrix.build_docs }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          HEX_FASTLY_KEY: ${{ secrets.HEX_FASTLY_KEY }}
        run: |
          version=$(echo ${{ github.ref_name }} | sed -e 's/^v//g')
          for f in doc/*; do
              if [ -d "$f" ]; then
                  app=`echo $f | sed s/"doc\/"//`
                  tar -czf "${app}-${version}.tar.gz" -C "doc/${app}" .
                  aws s3 cp "${app}-${version}.tar.gz" "s3://${{ env.AWS_S3_BUCKET }}/docs/${app}-${version}.tar.gz" \
                      --cache-control "public,max-age=3600" \
                      --metadata "{\"surrogate-key\":\"docs/${app}-${version}\",\"surrogate-control\":\"public,max-age=604800\"}"
                  curl \
                      -X POST \
                      -H "Fastly-Key: ${HEX_FASTLY_KEY}" \
                      -H "Accept: application/json" \
                      -H "Content-Length: 0" \
                      "https://api.fastly.com/service/${app}/purge/${version}"
              fi
          done
