name: Publish docs

on:
  push:
    branches:
      - main
      - v*.*

env:
  ELIXIR_OPTS: "--warnings-as-errors"
  ERLC_OPTS: "warnings_as_errors"
  LANG: C.UTF-8

jobs:
  release_pre_built:
    strategy:
      fail-fast: true
      matrix:
        include:
          - otp: 24
            otp_version: 24.3
          - otp: 25
            otp_version: 25.0
            build_docs: build_docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - uses: ./.github/workflows/release_pre_built
        with:
          otp_version: ${{ matrix.otp_version }}
          otp: ${{ matrix.otp }}
          build_docs: ${{ matrix.build_docs }}
      - name: Upload Docs to S3
        if: ${{ matrix.build_docs }}
        env:
          AWS_REGION: ${{ secrets.HEX_AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.HEX_AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FASTLY_SERVICE_ID: ${{ secrets.HEX_FASTLY_SERVICE_ID }}
          FASTLY_KEY: ${{ secrets.HEX_FASTLY_KEY }}
        run: |
          function purge_key() {
            curl \
                -X POST \
                -H "Fastly-Key: ${FASTLY_KEY}" \
                -H "Accept: application/json" \
                -H "Content-Length: 0" \
                "https://api.fastly.com/service/${FASTLY_SERVICE_ID}/purge/$1"
          }

          version=$(echo ${{ github.ref_name }} | sed -e 's/^v//g')
          for f in doc/*; do
              if [ -d "$f" ]; then
                  app=`echo $f | sed s/"doc\/"//`
                  tarball="${app}-${version}.tar.gz"
                  surrogate_key="docs/${app}-${version}"
                  tar -czf "${tarball}" -C "doc/${app}" .
                  aws s3 cp "${tarball}" "s3://${{ env.AWS_S3_BUCKET }}/docs/${tarball}" \
                      --cache-control "public,max-age=3600" \
                      --metadata "{\"surrogate-key\":\"${surrogate_key}\",\"surrogate-control\":\"public,max-age=604800\"}"
                  purge "${surrogate_key}"
                  sleep 2
                  purge "${surrogate_key}"
                  sleep 2
                  purge "${surrogate_key}"
              fi
          done
