# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2021 The Elixir Team

name: Release Notifications

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    name: Notify

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: "27.3"
          elixir-version: "1.18.3"

      - name: Run Elixir script
        env:
          ELIXIR_FORUM_TOKEN: ${{ secrets.ELIXIR_FORUM_TOKEN }}
          ELIXIR_LANG_ANN_TOKEN: ${{ secrets.ELIXIR_LANG_ANN_TOKEN }}
        run: |
          elixir .github/workflows/notify.exs "$GITHUB_REF_NAME"
