#!/bin/sh
readlink_f () {
  cd `dirname $1` > /dev/null
  local filename=`basename $1`
  if [ -h "$filename" ]; then
    readlink_f `readlink $filename`
  else
    echo "`pwd -P`/$filename"
  fi
}

SELF=`readlink_f $0`
SCRIPT_PATH=`dirname $SELF`
$SCRIPT_PATH/erl -env ERL_LIBS $SCRIPT_PATH/../lib -boot elixir -noinput $ELIXIR_ERL_OPTS -s elixir start_cli -extra --no-halt -e "Elixir.IEx.start" "$@"